# 3. Estructuras de datos 
Este capítulo describe algunas cosas que ya ha aprendido con más detalle y también agrega algunas cosas nuevas.

## 3.1. Más sobre Listas 
El tipo de datos de lista tiene algunos métodos más. Aquí están todos los métodos de objetos de lista:

`lista.append(x)`
> Agrega un elemento al final de la lista. Equivalente a `a[len(a):] = [x]`

`lista.extend(iterable)`
> Amplía la lista agregando todos los elementos del iterable. equivalente a `lista[len(lista):] = iterable`

`lista.insert(i, x)`
> Insertar un elemento en una posición determinada. El primer argumento es el índice del elemento antes del cual insertar, por lo que se inserta al principio de la lista y es equivalente a `lista.insert(0, x)`, y `lista.insert(len(a), x)` es equivalente `lista.append(x)`

`lista.remove(x)`
> Elimina el primer elemento de la lista cuyo valor es igual a `x`. Se genera un `ValueError` si no existe tal elemento.

`lista.pop([i])`
> Elimina el artículo en la posición dada en la lista y lo devuelve. Si no se especifica ningún índice, `lista.pop()` elimina y devuelve el último elemento de la lista. (Los corchetes alrededor de la i en la firma del método indican que el parámetro es opcional, no que deba escribir corchetes en esa posición. Verá esta notación con frecuencia en la Referencia de la biblioteca de Python).

`lista.clear()`
> Eliminar todos los elementos de la lista. equivalente a `del a[:]`

`lista.index(x[, inicio[, fin]])`
> Devuelve el índice, base-0, en la lista del primer elemento cuyo valor es igual a x. Genera un `ValueError` si no existe tal elemento.

> Los argumentos opcionales start y end se interpretan como en la notación de segmento y se utilizan para limitar la búsqueda a una subsecuencia particular de la lista. El índice devuelto se calcula en relación con el comienzo de la secuencia completa en lugar del argumento de inicio .

`lista.count(x)`
Devuelve el número de veces que x aparece en la lista.

`lista.sort( *, clave = Ninguno ,inverso = Falso)`
> Ordena los elementos de la lista.

`lista.reverse()`
> Invierte de posición los elementos de la lista.

`lista.copy()`
> Devuelve una copia superficial de la lista. Equivalente a `lista[:].`

Un ejemplo que utiliza la mayoría de los métodos de lista:

In [1]:
fruits = ['orange', 'apple', 'pear', 'banana', 'kiwi', 'apple', 'banana']
fruits.count('apple')

2

In [2]:
fruits.count('tangerine')

0

In [3]:
fruits.index('banana')

3

In [4]:
fruits.index('banana', 4)  # Find next banana starting at position 4

6

In [5]:
fruits.reverse()
fruits

['banana', 'apple', 'kiwi', 'banana', 'pear', 'apple', 'orange']

In [6]:
fruits.append('grape')
fruits

['banana', 'apple', 'kiwi', 'banana', 'pear', 'apple', 'orange', 'grape']

In [7]:
fruits.sort()
fruits

['apple', 'apple', 'banana', 'banana', 'grape', 'kiwi', 'orange', 'pear']

In [8]:
fruits.pop()

'pear'

In [9]:
fruits

['apple', 'apple', 'banana', 'banana', 'grape', 'kiwi', 'orange']

Es posible que haya notado que los métodos como `insert`, `remove` o `sort` que solo modifican la lista no tienen un valor de retorno impreso; devuelven el valor predeterminado None. Este es un principio de diseño para todas las estructuras de datos mutables en Python.

Otra cosa que puede notar es que no todos los datos se pueden ordenar o comparar. Por ejemplo, `[None. 'hello', 10]` no se puede ordenar porque los números enteros no se pueden comparar con cadenas y `None` no se puede comparar con otros tipos. Además, hay algunos tipos que no tienen una relación de orden definida. Por ejemplo, `3+4j < 5+7j` no es una comparación válida 

### 3.1.1. Usando Listas como Pilas 

Los métodos de lista facilitan mucho el uso de una lista como una pila, donde el último elemento agregado es el primer elemento recuperado (LIFO - *Last In, First Out*, "el último en entrar, primero en salir"). Para agregar un elemento a la parte superior de la pila, use `append()`. Para recuperar un elemento de la parte superior de la pila, utilícelo `pop()` sin un índice explícito. Por ejemplo:

In [10]:
stack = [3, 4, 5]
stack.append(6)
stack.append(7)
stack

[3, 4, 5, 6, 7]

In [11]:
stack.pop()

7

In [12]:
stack

[3, 4, 5, 6]

In [13]:
stack.pop()
stack.pop()
stack

[3, 4]

### 3.1.2. Usando Listas como Colas 

También es posible utilizar una lista como una cola, donde el primer elemento agregado es el primer elemento recuperado (FIFO - *First In, First Out* "primero en entrar, primero en salir"); sin embargo, las listas no son eficientes para este propósito. Si bien las anexiones y los elementos emergentes desde el final de la lista son rápidos, hacer inserciones o elementos emergentes desde el principio de una lista es lento (porque todos los demás elementos tienen que ser desplazados por uno).

Para implementar una cola, use `collections.deque` que fue diseñada para tener agregados y mensajes emergentes rápidos desde ambos extremos. Por ejemplo:

In [14]:
from collections import deque
queue = deque(["Eric", "John", "Michael"])
queue.append("Terry")           # Terry arrives
queue.append("Graham")          # Graham arrives
queue.popleft()                 # The first to arrive now leaves

'Eric'

In [15]:
queue.popleft()                 # The second to arrive now leaves

'John'

In [16]:
queue

deque(['Michael', 'Terry', 'Graham'])

### 3.1.3. Comprensiones de lista 
Las listas de comprensión proporcionan una forma concisa de crear listas. Las aplicaciones comunes son hacer nuevas listas donde cada elemento es el resultado de algunas operaciones aplicadas a cada miembro de otra secuencia o iterable, o crear una subsecuencia de esos elementos que satisfacen una determinada condición.

Por ejemplo, supongamos que queremos crear una lista de cuadrados, como:

In [17]:
squares = []
for x in range(10):
    squares.append(x**2)

squares

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

Tenga en cuenta que esto crea (o sobrescribe) una variable nombrada `x` que aún existe después de que se completa el ciclo. Podemos calcular la lista de cuadrados sin ningún efecto secundario usando:

In [22]:
squares = [x**2 for x in range(15)]
squares

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196]

Una lista por comprensión consta de corchetes que contienen una expresión seguida de una cláusula `for`, luego cero o más cláusulas `for` o `if`. El resultado será una nueva lista resultante de evaluar la expresión en el contexto de las cláusulas `for` e `if` que la siguen. Por ejemplo, este `listcomp` combina los elementos de dos listas si no son iguales:

In [23]:
[(x, y) for x in [1,2,3] for y in [3,1,4] if x != y]

[(1, 3), (1, 4), (2, 3), (2, 1), (2, 4), (3, 1), (3, 4)]

que es equivalente a:

In [24]:
combs = []
for x in [1,2,3]:
    for y in [3,1,4]:
        if x != y:
            combs.append((x, y))

combs

[(1, 3), (1, 4), (2, 3), (2, 1), (2, 4), (3, 1), (3, 4)]

Observe cómo el orden de las declaraciones `for` e `if` es el mismo en ambos fragmentos.

Si la expresión es una tupla (por ejemplo, la del ejemplo anterior), debe estar entre paréntesis.`(x, y)`

In [25]:
vec = [-4, -2, 0, 2, 4]
# create a new list with the values doubled
[x*2 for x in vec]

[-8, -4, 0, 4, 8]

In [26]:
# filter the list to exclude negative numbers
[x for x in vec if x >= 0]

[0, 2, 4]

In [27]:
# apply a function to all the elements
[abs(x) for x in vec]

[4, 2, 0, 2, 4]

In [28]:
# call a method on each element
freshfruit = ['  banana', '  loganberry ', 'passion fruit  ']
[weapon.strip() for weapon in freshfruit]

['banana', 'loganberry', 'passion fruit']

In [29]:
# create a list of 2-tuples like (number, square)
[(x, x**2) for x in range(6)]

[(0, 0), (1, 1), (2, 4), (3, 9), (4, 16), (5, 25)]

In [30]:
# the tuple must be parenthesized, otherwise an error is raised
[x, x**2 for x in range(6)]

SyntaxError: ignored

In [31]:
# flatten a list using a listcomp with two 'for'
vec = [[1,2,3], [4,5,6], [7,8,9]]
[num for elem in vec for num in elem]

[1, 2, 3, 4, 5, 6, 7, 8, 9]

Las listas por comprensión pueden contener expresiones complejas y funciones anidadas:



In [32]:
from math import pi
[str(round(pi, i)) for i in range(1, 6)]

['3.1', '3.14', '3.142', '3.1416', '3.14159']

### 3.1.4. Comprensiones de listas anidadas

La expresión inicial en una lista por comprensión puede ser cualquier expresión arbitraria, incluida otra lista por comprensión.

Considere el siguiente ejemplo de una matriz de 3x4 implementada como una lista de 3 listas de longitud 4:

In [37]:
matrix = [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
]

La siguiente lista de comprensión transpondrá filas y columnas:

In [34]:
[[row[i] for row in matrix] for i in range(4)]

[[1, 5, 9], [2, 6, 10], [3, 7, 11], [4, 8, 12]]

Como vimos en el apartado anterior, la comprensión de la lista interna se evalúa en el contexto del `for` que le sigue, por lo que este ejemplo equivale a:

In [38]:
transposed = []
for i in range(4):
    transposed.append([row[i] for row in matrix])

transposed

[[1, 5, 9], [2, 6, 10], [3, 7, 11], [4, 8, 12]]

que, a su vez, es lo mismo que:

In [39]:
transposed = []
for i in range(4):
    # the following 3 lines implement the nested listcomp
    transposed_row = []
    for row in matrix:
        transposed_row.append(row[i])
    transposed.append(transposed_row)

transposed

[[1, 5, 9], [2, 6, 10], [3, 7, 11], [4, 8, 12]]

## 3.2. La declaración `del`

Hay una forma de eliminar un elemento de una lista dado su índice en lugar de su valor: la declaración `del`. Esto difiere del método `pop()` que devuelve un valor. La declaración `del` también se puede usar para eliminar sectores de una lista o borrar toda la lista (lo que hicimos anteriormente mediante la asignación de una lista vacía al sector). Por ejemplo:

In [40]:
a = [-1, 1, 66.25, 333, 333, 1234.5]
del a[0]
a

[1, 66.25, 333, 333, 1234.5]

In [41]:
del a[2:4]
a

[1, 66.25, 1234.5]

In [42]:
del a[:]
a

[]

## 3.3. Tuplas y Secuencias 

Vimos que las listas y las cadenas tienen muchas propiedades comunes, como las operaciones de indexación y división. Son dos ejemplos de tipos de datos de secuencia. Dado que Python es un lenguaje en evolución, se pueden agregar otros tipos de datos de secuencia. También hay otro tipo de datos de secuencia estándar: la tupla.

Una tupla consta de una serie de valores separados por comas, por ejemplo:

In [43]:
t = 12345, 54321, 'hello!'
t[0]

12345

In [44]:
t

(12345, 54321, 'hello!')

In [45]:
# Tuples may be nested:
u = t, (1, 2, 3, 4, 5)
u

((12345, 54321, 'hello!'), (1, 2, 3, 4, 5))

In [46]:
# Tuples are immutable:
t[0] = 88888

TypeError: ignored

In [47]:
# but they can contain mutable objects:
v = ([1, 2, 3], [3, 2, 1])
v

([1, 2, 3], [3, 2, 1])

Como puede ver, en la salida, las tuplas siempre se encierran entre paréntesis, para que las tuplas anidadas se interpreten correctamente; se pueden ingresar con o sin paréntesis, aunque a menudo los paréntesis son necesarios de todos modos (si la tupla es parte de una expresión más grande). No es posible asignar a los elementos individuales de una tupla, sin embargo, es posible crear tuplas que contengan objetos mutables, como listas.

Aunque las tuplas pueden parecer similares a las listas, a menudo se usan en diferentes situaciones y para diferentes propósitos. Las tuplas son *inmutables* y, por lo general, contienen una secuencia heterogénea de elementos a los que se accede mediante desempaquetado o indexación. Las listas son *mutables* y sus elementos suelen ser homogéneos y se accede a ellos iterando sobre la lista.

Un problema especial es la construcción de tuplas que contienen 0 o 1 elementos: la sintaxis tiene algunas peculiaridades adicionales para acomodarlos. Las tuplas vacías se construyen con un par de paréntesis vacíos; una tupla con un elemento se construye siguiendo un valor con una coma (no es suficiente encerrar un solo valor entre paréntesis). Feo, pero efectivo. Por ejemplo:

In [48]:
empty = ()
singleton = 'hello',    # <-- note trailing comma
len(empty)

0

In [49]:
len(singleton)

1

In [50]:
singleton

('hello',)

la instrucción `t = 12345, 54321, 'hello!'` es un ejemplo de empaquetamiento de tuplas: los valores `12345`, `54321` y `'hello!'` son empaquetados juntos en una tupla. La operación inversa también es posible:

In [52]:
t = 12345, 54321, 'hello!'
t

(12345, 54321, 'hello!')

In [54]:
x, y, z = t
z

'hello!'

Esto se llama, apropiadamente, desempaquetado de secuencias y funciona para cualquier secuencia en el lado derecho. El desempaquetado de secuencias requiere que haya tantas variables en el lado izquierdo del signo igual como elementos hay en la secuencia. Tenga en cuenta que la asignación múltiple es realmente solo una combinación de empaquetado de tuplas y desempaquetado de secuencias

## 3.4. Conjuntos 

Python también incluye un tipo de datos para conjuntos. Un conjunto es una colección desordenada sin elementos duplicados. Los usos básicos incluyen pruebas de membresía y eliminación de entradas duplicadas. Los objetos establecidos también admiten operaciones matemáticas como unión, intersección, diferencia y diferencia simétrica.

Las llaves o la función `set()` se pueden usar para crear conjuntos. Nota: para crear un conjunto vacío, debe usar `set()`, no `{}`; este último crea un diccionario vacío, una estructura de datos que discutiremos en la siguiente sección.

Aquí hay una breve demostración:

In [56]:
basket = {'apple', 'orange', 'apple', 'pear', 'orange', 'banana'}
print(basket)                      # show that duplicates have been removed

{'apple', 'orange', 'banana', 'pear'}


{'apple', 'banana', 'orange', 'pear'}

In [57]:
'orange' in basket                 # fast membership testing

True

In [58]:
'crabgrass' in basket

False

In [59]:
a = set('abracadabra')
b = set('alacazam')

In [60]:
a                                  # unique letters in a

{'a', 'b', 'c', 'd', 'r'}

In [61]:
a - b                              # letters in a but not in b

{'b', 'd', 'r'}

In [62]:
a | b                              # letters in a or b or both

{'a', 'b', 'c', 'd', 'l', 'm', 'r', 'z'}

In [63]:
a & b                              # letters in both a and b

{'a', 'c'}

In [64]:
a ^ b                              # letters in a or b but not both

{'b', 'd', 'l', 'm', 'r', 'z'}

De manera similar a las comprensiones de listas , también se admiten las comprensiones de conjuntos:

In [65]:
a = {x for x in 'abracadabra' if x not in 'abc'}
a

{'d', 'r'}

## 3.5. Diccionarios 

Otro tipo de datos útil integrado en Python es el diccionario. Los diccionarios a veces se encuentran en otros idiomas como "memorias asociativas" o "matrices asociativas". A diferencia de las secuencias, que están indexadas por un rango de números, los diccionarios están indexados por claves, que pueden ser de cualquier tipo inmutable; cadenas y números siempre pueden ser claves. Las tuplas se pueden usar como claves si solo contienen cadenas, números o tuplas; si una tupla contiene cualquier objeto mutable, ya sea directa o indirectamente, no se puede usar como clave. No puede usar listas como claves, ya que las listas se pueden modificar en su lugar mediante asignaciones de índice, asignaciones de sectores o métodos como append()y extend().

Es mejor pensar en un diccionario como un conjunto de parejas clave:valor, con el requisito de que las claves sean únicas (dentro de un diccionario). Un par de llaves crea un diccionario vacío: `{}`. Colocar una lista separada por comas de pares `clave:valor` entre llaves agrega pares iniciales `clave:valor` al diccionario; esta es también la forma en que se escriben los diccionarios en la salida.

Las operaciones principales en un diccionario son almacenar un valor con alguna clave y extraer el valor dada una clave. También es posible eliminar un par `clave:valor` con `del`. Si almacena usando una clave que ya está en uso, el valor anterior asociado con esa clave se olvida. Es un error extraer un valor utilizando una clave inexistente.

Realizar `list(d)` en un diccionario devuelve una lista de todas las claves utilizadas en el diccionario, en orden de inserción (si desea ordenarlas, simplemente utilice `sorted(d)` en su lugar). Para verificar si una sola clave está en el diccionario, use la inpalabra clave.

Aquí hay un pequeño ejemplo usando un diccionario:

In [66]:
tel = {'jack': 4098, 'sape': 4139}
tel['guido'] = 4127
tel

{'jack': 4098, 'sape': 4139, 'guido': 4127}

In [67]:
tel['jack']

4098

In [68]:
del tel['sape']
tel['irv'] = 4127
tel

{'jack': 4098, 'guido': 4127, 'irv': 4127}

In [69]:
list(tel)

['jack', 'guido', 'irv']

In [70]:
sorted(tel)

['guido', 'irv', 'jack']

In [71]:
'guido' in tel

True

In [72]:
'jack' not in tel

False

El constructor `dict()` crea diccionarios directamente a partir de secuencias de pares clave-valor:

In [73]:
dict([('sape', 4139), ('guido', 4127), ('jack', 4098)])

{'sape': 4139, 'guido': 4127, 'jack': 4098}

Además, las compresiones de dictado se pueden usar para crear diccionarios a partir de expresiones arbitrarias de clave y valor:

In [74]:
{x: x**2 for x in (2, 4, 6)}

{2: 4, 4: 16, 6: 36}

Cuando las claves son cadenas simples, a veces es más fácil especificar pares usando argumentos de palabras clave:

In [75]:
dict(sape=4139, guido=4127, jack=4098)

{'sape': 4139, 'guido': 4127, 'jack': 4098}

## 3.6. Técnicas de bucle 
Al recorrer los diccionarios, la clave y el valor correspondiente se pueden recuperar al mismo tiempo usando el método `items()`.

In [76]:
knights = {'gallahad': 'the pure', 'robin': 'the brave'}
for k, v in knights.items():
    print(k, v)

gallahad the pure
robin the brave


Al recorrer una secuencia, el índice de posición y el valor correspondiente se pueden recuperar al mismo tiempo usando la función `enumerate()`.

In [77]:
for i, v in enumerate(['tic', 'tac', 'toe']):
    print(i, v)

0 tic
1 tac
2 toe


Para recorrer dos o más secuencias al mismo tiempo, las entradas se pueden emparejar con la función `zip()`.

In [78]:
questions = ['name', 'quest', 'favorite color']
answers = ['lancelot', 'the holy grail', 'blue']
for q, a in zip(questions, answers):
    print('What is your {0}?  It is {1}.'.format(q, a))

What is your name?  It is lancelot.
What is your quest?  It is the holy grail.
What is your favorite color?  It is blue.


Para recorrer una secuencia en sentido inverso, primero especifique la secuencia en dirección hacia adelante y luego llame a la función `reversed()`.

In [79]:
for i in reversed(range(1, 10, 2)):
    print(i)

9
7
5
3
1


Para recorrer una secuencia en orden, use la función `sorted()` que devuelve una nueva lista ordenada sin modificar la fuente.

In [80]:
basket = ['apple', 'orange', 'apple', 'pear', 'orange', 'banana']
for i in sorted(basket):
    print(i)

apple
apple
banana
orange
orange
pear


Usar `set()` en una secuencia elimina los elementos duplicados. El uso de `sorted()` en combinación con `set()` sobre una secuencia es una forma idiomática de recorrer elementos únicos de la secuencia en orden ordenado.

In [81]:
basket = ['apple', 'orange', 'apple', 'pear', 'orange', 'banana']
for f in sorted(set(basket)):
    print(f)

apple
banana
orange
pear


## 3.7. Más sobre Condiciones 

Las condiciones utilizadas en las declaraciones `while` e `if` pueden contener cualquier operador, no solo comparaciones.

Los operadores de comparación `in` y `not in` son pruebas de membresía que determinan si un valor está (o no) en un contenedor. Los operadores `is` y `is not` comparan si dos objetos son realmente el mismo objeto. Todos los operadores de comparación tienen la misma prioridad, que es inferior a la de todos los operadores numéricos.

Las comparaciones se pueden encadenar. Por ejemplo, `a < b == cabbc` prueba si `a` es menor que `b` y además es igual a `c`.

Las comparaciones pueden combinarse utilizando los operadores booleanos `and` y `or`, y el resultado de una comparación (o de cualquier otra expresión booleana) puede negarse con `not`. Estos tienen prioridades más bajas que los operadores de comparación; entre ellos, `not` tiene la prioridad más alta y `or` la más baja, por lo que `A and not B or C` es equivalente a `(A and (not B)) or C`. Como siempre, se pueden usar paréntesis para expresar la composición deseada.

Los operadores booleanos `and` y `or` son los llamados operadores de corto circuito: sus argumentos se evalúan de izquierda a derecha y la evaluación se detiene tan pronto como se determina el resultado. Por ejemplo, si `A` y `C` es verdadero pero `B` es falso, `A and B and C` no evalúa la expresión `C`. Cuando se usa como valor general y no como booleano, el valor de retorno de un operador de cortocircuito es el último argumento evaluado.

Es posible asignar el resultado de una comparación u otra expresión booleana a una variable. Por ejemplo,

In [82]:
string1, string2, string3 = '', 'Trondheim', 'Hammer Dance'
non_null = string1 or string2 or string3
non_null

'Trondheim'

Tenga en cuenta que en Python, a diferencia de C, la asignación dentro de las expresiones debe hacerse explícitamente con el operador morsa `:=` . Esto evita una clase común de problemas que se encuentran en los programas C: escribir una expresión `=` cuando se pretendía `==`.

## 3.8. Comparando Secuencias y Otros Tipos 

Los objetos de secuencia normalmente se pueden comparar con otros objetos con el mismo tipo de secuencia. La comparación utiliza una ordenación lexicográfica: primero se comparan los dos primeros elementos, y si difieren esto determina el resultado de la comparación; si son iguales, se comparan los dos elementos siguientes, y así sucesivamente, hasta agotar cualquiera de las secuencias. Si dos elementos a comparar son en sí mismos secuencias del mismo tipo, la comparación lexicográfica se realiza recursivamente. Si todos los elementos de dos secuencias son iguales, las secuencias se consideran iguales. Si una secuencia es una subsecuencia inicial de la otra, la secuencia más corta es la más pequeña (menor). La ordenación lexicográfica de cadenas utiliza el número de punto de código Unicode para ordenar caracteres individuales. Algunos ejemplos de comparaciones entre secuencias del mismo tipo:



```
(1, 2, 3)              < (1, 2, 4)
[1, 2, 3]              < [1, 2, 4]
'ABC' < 'C' < 'Pascal' < 'Python'
(1, 2, 3, 4)           < (1, 2, 4)
(1, 2)                 < (1, 2, -1)
(1, 2, 3)             == (1.0, 2.0, 3.0)
(1, 2, ('aa', 'ab'))   < (1, 2, ('abc', 'a'), 4)
```

Tenga en cuenta que comparar objetos de diferentes tipos con < o > es legal siempre que los objetos tengan métodos de comparación apropiados. Por ejemplo, los tipos numéricos mixtos se comparan según su valor numérico, por lo que 0 es igual a 0.0, etc. De lo contrario, en lugar de proporcionar un orden arbitrario, el intérprete generará una excepción `TypeError`.

